package main

import (
	"slices"
	"testing"

	"github.com/radiergummi/cetacean/internal/spec"
)

func TestOverlap(t *testing.T) {
	const statement = `If the values are not equal, an error response indicating ` +
		`"invalid_grant" as described in Section 5.2 of [RFC6749] MUST be returned.`

	cases := map[string]struct {
		entry string
		held  bool
	}{
		// The registry drops the citation and reflows the rest, which is what
		// an entry quoting this sentence looks like.
		"an elided quote": {
			entry: `If the values are not equal, an error response indicating ` +
				`"invalid_grant" MUST be returned.`,
			held: true,
		},
		"a different requirement": {
			entry: `The authorization server MUST NOT issue an access token that is ` +
				`valid for resources other than those the client requested.`,
			held: false,
		},
		// Same words, opposite rule. A set comparison calls these equal.
		"the sentence reversed": {
			entry: `MUST be returned an error response indicating not equal values ` +
				`are the if`,
			held: false,
		},
	}

	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			if got := overlap(words(statement), words(tc.entry)) >= minOverlap; got != tc.held {
				t.Errorf("held = %v, want %v (score %.2f)",
					got, tc.held, overlap(words(statement), words(tc.entry)))
			}
		})
	}
}

// A parameter declaration is two words, and two words are a subsequence of
// almost any sentence. The entry quoting one opens with it.
func TestAShortStatementIsAnchoredToTheOpening(t *testing.T) {
	opens := `"code": REQUIRED. The authorization code is generated by the ` +
		`authorization server and opaque to the client.`
	mentions := `The authorization server MUST associate the code_challenge with ` +
		`the issued authorization code, which is REQUIRED.`

	if overlap(words(`"code": REQUIRED.`), words(opens)) < minOverlap {
		t.Error("an entry opening with the declaration does not hold it")
	}
	if overlap(words(`"code": REQUIRED.`), words(mentions)) >= minOverlap {
		t.Error("an entry merely containing both words holds it")
	}
}

func TestReconcileFindsAnEntryTheDocumentDoesNotState(t *testing.T) {
	doc := &spec.Document{
		Requirements: []spec.Requirement{
			{ID: "quoted", Text: "The server MUST answer every request it routes."},
			{ID: "drifted", Text: "The server MUST refuse a request carrying two tokens."},
		},
	}

	unheld, unquoted := Reconcile([]string{
		"The server MUST answer every request it routes.",
		"The server MUST close a stream it is done with.",
	}, doc)

	if want := []string{"drifted"}; !slices.Equal(unquoted, want) {
		t.Errorf("unquoted = %q, want %q", unquoted, want)
	}

	if want := []string{"The server MUST close a stream it is done with."}; !slices.Equal(
		unheld, want) {
		t.Errorf("unheld = %q, want %q", unheld, want)
	}
}

// Two entries can open with the same parameter name. One sentence reaches
// both, so neither reads as drift — which a matcher picking a single winner
// per statement would get wrong.
func TestOneStatementReachesEveryEntryItQuotes(t *testing.T) {
	doc := &spec.Document{
		Requirements: []spec.Requirement{
			{ID: "first", Text: `"error": REQUIRED. A single ASCII error code.`},
			{ID: "second", Text: `"error": REQUIRED. The same code, on the other endpoint.`},
		},
	}

	if _, unquoted := Reconcile([]string{`"error": REQUIRED.`}, doc); len(unquoted) != 0 {
		t.Errorf("unquoted = %q, want none", unquoted)
	}
}
