export interface Property {
  name: string;
  iri: string;
  description: string;
  expectedType: string;
  usedOn: string[];
  container?: "@set" | "@list";
}

export interface ResourceType {
  name: string;
  description: string;
  endpoint: string;
  properties: string[];
}

export const properties: Property[] = [
  {
    name: "action",
    iri: "urn:cetacean:action",
    description: "The action performed on a resource (create, update, remove).",
    expectedType: "String",
    usedOn: ["HistoryEntry"],
  },
  {
    name: "aliases",
    iri: "urn:cetacean:aliases",
    description: "DNS aliases for a service on a given network.",
    expectedType: "Array of String",
    usedOn: ["Service"],
  },
  {
    name: "availability",
    iri: "urn:cetacean:availability",
    description: "The scheduling availability of a node: `active`, `pause`, or `drain`.",
    expectedType: "String",
    usedOn: ["Node"],
  },
  {
    name: "buildDate",
    iri: "urn:cetacean:buildDate",
    description: "Build timestamp of the running binary.",
    expectedType: "String",
    usedOn: ["Health"],
  },
  {
    name: "changes",
    iri: "urn:cetacean:changes",
    description: "Spec changes from the previous service version.",
    expectedType: "Array",
    usedOn: ["Service"],
    container: "@list",
  },
  {
    name: "commit",
    iri: "urn:cetacean:commit",
    description: "Git commit SHA of the build.",
    expectedType: "String",
    usedOn: ["Health"],
  },
  {
    name: "computedAt",
    iri: "urn:cetacean:computedAt",
    description: "Timestamp when recommendations were last computed.",
    expectedType: "DateTime",
    usedOn: ["RecommendationCollection"],
  },
  {
    name: "config",
    iri: "urn:cetacean:config",
    description: "The Docker config object.",
    expectedType: "Object",
    usedOn: ["Config"],
  },
  {
    name: "configs",
    iri: "urn:cetacean:configs",
    description: "Config references attached to a service.",
    expectedType: "Array",
    usedOn: ["ServiceConfigs"],
    container: "@list",
  },
  {
    name: "counts",
    iri: "urn:cetacean:counts",
    description: "Result counts per resource type.",
    expectedType: "Object",
    usedOn: ["SearchResult"],
  },
  {
    name: "driver",
    iri: "urn:cetacean:driver",
    description: "The driver backing a network or volume (e.g., `overlay`, `local`).",
    expectedType: "String",
    usedOn: ["Network", "Volume"],
  },
  {
    name: "endpointMode",
    iri: "urn:cetacean:endpointMode",
    description: "Endpoint mode for a service: `vip` or `dnsrr`.",
    expectedType: "String",
    usedOn: ["ServiceEndpointMode"],
  },
  {
    name: "env",
    iri: "urn:cetacean:env",
    description: "Environment variables as a key-value map.",
    expectedType: "Object",
    usedOn: ["ServiceEnv"],
  },
  {
    name: "healthcheck",
    iri: "urn:cetacean:healthcheck",
    description: "Container healthcheck configuration.",
    expectedType: "Object",
    usedOn: ["ServiceHealthcheck"],
  },
  {
    name: "hostname",
    iri: "urn:cetacean:hostname",
    description: "Node hostname in a task cross-reference.",
    expectedType: "String",
    usedOn: ["Task"],
  },
  {
    name: "image",
    iri: "urn:cetacean:image",
    description: "The container image reference (registry/name:tag@digest).",
    expectedType: "String",
    usedOn: ["Service", "Task"],
  },
  {
    name: "integrations",
    iri: "urn:cetacean:integrations",
    description: "Detected third-party integrations for a service.",
    expectedType: "Array",
    usedOn: ["Service"],
    container: "@list",
  },
  {
    name: "isLeader",
    iri: "urn:cetacean:isLeader",
    description: "Whether this manager node is the Raft leader.",
    expectedType: "Boolean",
    usedOn: ["NodeRole"],
  },
  {
    name: "items",
    iri: "urn:cetacean:items",
    description: "The set of resources in a collection response.",
    expectedType: "Array",
    usedOn: ["Collection", "RecommendationCollection"],
    container: "@set",
  },
  {
    name: "kind",
    iri: "urn:cetacean:kind",
    description: "The resource kind for history and SSE events (e.g., `service`, `node`).",
    expectedType: "String",
    usedOn: ["HistoryEntry"],
  },
  {
    name: "labels",
    iri: "urn:cetacean:labels",
    description: "Labels as a key-value map.",
    expectedType: "Object",
    usedOn: ["ServiceLabels", "NodeLabels"],
  },
  {
    name: "limit",
    iri: "urn:cetacean:limit",
    description: "Page size limit for a collection response.",
    expectedType: "Integer",
    usedOn: ["Collection"],
  },
  {
    name: "logDriver",
    iri: "urn:cetacean:logDriver",
    description: "Log driver name and options.",
    expectedType: "Object",
    usedOn: ["ServiceLogDriver"],
  },
  {
    name: "managerAddr",
    iri: "urn:cetacean:managerAddr",
    description: "Manager node address for remote Docker API access.",
    expectedType: "String",
    usedOn: ["Swarm"],
  },
  {
    name: "managerCount",
    iri: "urn:cetacean:managerCount",
    description: "Total number of manager nodes in the swarm.",
    expectedType: "Integer",
    usedOn: ["NodeRole"],
  },
  {
    name: "maxNodeCPU",
    iri: "urn:cetacean:maxNodeCPU",
    description: "CPU capacity (nanoCPUs) of the largest node in the cluster.",
    expectedType: "Integer",
    usedOn: ["ClusterCapacity"],
  },
  {
    name: "maxNodeMemory",
    iri: "urn:cetacean:maxNodeMemory",
    description: "Memory capacity (bytes) of the largest node in the cluster.",
    expectedType: "Integer",
    usedOn: ["ClusterCapacity"],
  },
  {
    name: "mode",
    iri: "urn:cetacean:mode",
    description: "The scheduling mode of a service: `replicated` or `global`.",
    expectedType: "String",
    usedOn: ["Service", "ServiceMode"],
  },
  {
    name: "mounts",
    iri: "urn:cetacean:mounts",
    description: "Mount configuration attached to a service.",
    expectedType: "Array",
    usedOn: ["ServiceMounts"],
    container: "@list",
  },
  {
    name: "name",
    iri: "urn:cetacean:name",
    description: "The human-readable name of a resource. For nodes this is the hostname; for services, configs, secrets, networks, and volumes it is the Docker object name.",
    expectedType: "String",
    usedOn: ["Node", "Service", "Stack", "Config", "Secret", "Network", "Volume", "ServiceRef"],
  },
  {
    name: "network",
    iri: "urn:cetacean:network",
    description: "The Docker network object.",
    expectedType: "Object",
    usedOn: ["Network"],
  },
  {
    name: "networks",
    iri: "urn:cetacean:networks",
    description: "The networks a service is attached to.",
    expectedType: "Array of NetworkAttachment",
    usedOn: ["Service", "ServiceNetworks"],
    container: "@list",
  },
  {
    name: "node",
    iri: "urn:cetacean:node",
    description: "The Docker node object.",
    expectedType: "Object",
    usedOn: ["Node"],
  },
  {
    name: "nodeCount",
    iri: "urn:cetacean:nodeCount",
    description: "Number of nodes in the cluster.",
    expectedType: "Integer",
    usedOn: ["Cluster", "ClusterCapacity"],
  },
  {
    name: "nodesDown",
    iri: "urn:cetacean:nodesDown",
    description: "Number of nodes in down state.",
    expectedType: "Integer",
    usedOn: ["Cluster"],
  },
  {
    name: "nodesDraining",
    iri: "urn:cetacean:nodesDraining",
    description: "Number of nodes in drain state.",
    expectedType: "Integer",
    usedOn: ["Cluster"],
  },
  {
    name: "nodesReady",
    iri: "urn:cetacean:nodesReady",
    description: "Number of nodes in ready state.",
    expectedType: "Integer",
    usedOn: ["Cluster"],
  },
  {
    name: "offset",
    iri: "urn:cetacean:offset",
    description: "Page offset for a collection response.",
    expectedType: "Integer",
    usedOn: ["Collection"],
  },
  {
    name: "operationsLevel",
    iri: "urn:cetacean:operationsLevel",
    description: "Current operations level (0=read-only, 1=operational, 2=configuration, 3=impactful).",
    expectedType: "Integer",
    usedOn: ["Health"],
  },
  {
    name: "placement",
    iri: "urn:cetacean:placement",
    description: "Placement constraints and preferences for a service.",
    expectedType: "Object",
    usedOn: ["ServicePlacement"],
  },
  {
    name: "plugin",
    iri: "urn:cetacean:plugin",
    description: "The Docker plugin object.",
    expectedType: "Object",
    usedOn: ["Plugin"],
  },
  {
    name: "ports",
    iri: "urn:cetacean:ports",
    description: "Published port bindings for a service, ordered by target port.",
    expectedType: "Array of PortConfig",
    usedOn: ["Service", "ServicePorts"],
    container: "@list",
  },
  {
    name: "prometheusConfigured",
    iri: "urn:cetacean:prometheusConfigured",
    description: "Whether a Prometheus instance is configured.",
    expectedType: "Boolean",
    usedOn: ["Cluster"],
  },
  {
    name: "query",
    iri: "urn:cetacean:query",
    description: "The search query string.",
    expectedType: "String",
    usedOn: ["SearchResult"],
  },
  {
    name: "replicas",
    iri: "urn:cetacean:replicas",
    description: "The configured number of replicas for a replicated service.",
    expectedType: "Integer",
    usedOn: ["Service", "ServiceMode"],
  },
  {
    name: "requestId",
    iri: "urn:cetacean:requestId",
    description: "Unique request identifier for error correlation.",
    expectedType: "String",
    usedOn: ["ProblemDetail"],
  },
  {
    name: "reservedCPU",
    iri: "urn:cetacean:reservedCPU",
    description: "Total reserved CPU (nanoCPUs) across all services.",
    expectedType: "Integer",
    usedOn: ["Cluster"],
  },
  {
    name: "reservedMemory",
    iri: "urn:cetacean:reservedMemory",
    description: "Total reserved memory (bytes) across all services.",
    expectedType: "Integer",
    usedOn: ["Cluster"],
  },
  {
    name: "resourceId",
    iri: "urn:cetacean:resourceId",
    description: "The ID of the affected resource.",
    expectedType: "String",
    usedOn: ["HistoryEntry"],
  },
  {
    name: "resources",
    iri: "urn:cetacean:resources",
    description: "CPU/memory reservations and limits for a service.",
    expectedType: "Object",
    usedOn: ["ServiceResources"],
  },
  {
    name: "results",
    iri: "urn:cetacean:results",
    description: "Search results grouped by resource type.",
    expectedType: "Object",
    usedOn: ["SearchResult"],
  },
  {
    name: "role",
    iri: "urn:cetacean:role",
    description: "The role of a node in the swarm: `manager` or `worker`.",
    expectedType: "String",
    usedOn: ["Node", "NodeRole"],
  },
  {
    name: "rollbackPolicy",
    iri: "urn:cetacean:rollbackPolicy",
    description: "Rollback configuration for a service.",
    expectedType: "Object",
    usedOn: ["ServiceRollbackPolicy"],
  },
  {
    name: "scope",
    iri: "urn:cetacean:scope",
    description: "The scope of a network or volume: `swarm` or `local`.",
    expectedType: "String",
    usedOn: ["Network", "Volume"],
  },
  {
    name: "secret",
    iri: "urn:cetacean:secret",
    description: "The Docker secret object (data always redacted).",
    expectedType: "Object",
    usedOn: ["Secret"],
  },
  {
    name: "secrets",
    iri: "urn:cetacean:secrets",
    description: "Secret references attached to a service.",
    expectedType: "Array",
    usedOn: ["ServiceSecrets"],
    container: "@list",
  },
  {
    name: "service",
    iri: "urn:cetacean:service",
    description: "The Docker service object.",
    expectedType: "Object",
    usedOn: ["Service"],
  },
  {
    name: "serviceCount",
    iri: "urn:cetacean:serviceCount",
    description: "Number of services in the cluster.",
    expectedType: "Integer",
    usedOn: ["Cluster"],
  },
  {
    name: "services",
    iri: "urn:cetacean:services",
    description: "Cross-referenced services using this resource.",
    expectedType: "Array of ServiceRef",
    usedOn: ["Config", "Secret", "Network", "Volume"],
    container: "@list",
  },
  {
    name: "servicesConverged",
    iri: "urn:cetacean:servicesConverged",
    description: "Number of services with all tasks running.",
    expectedType: "Integer",
    usedOn: ["Cluster"],
  },
  {
    name: "servicesDegraded",
    iri: "urn:cetacean:servicesDegraded",
    description: "Number of services with fewer tasks than desired.",
    expectedType: "Integer",
    usedOn: ["Cluster"],
  },
  {
    name: "slot",
    iri: "urn:cetacean:slot",
    description: "The slot number of a task within a replicated service. Each replica occupies a unique slot.",
    expectedType: "Integer",
    usedOn: ["Task"],
  },
  {
    name: "stack",
    iri: "urn:cetacean:stack",
    description: "The stack detail with member resources.",
    expectedType: "Object",
    usedOn: ["Stack"],
  },
  {
    name: "stackCount",
    iri: "urn:cetacean:stackCount",
    description: "Number of stacks in the cluster.",
    expectedType: "Integer",
    usedOn: ["Cluster"],
  },
  {
    name: "state",
    iri: "urn:cetacean:state",
    description: "The current state of a resource. For nodes: `ready`, `down`, or `unknown`. For tasks: `running`, `failed`, `complete`, etc. For services: a derived state based on running/desired task counts.",
    expectedType: "String",
    usedOn: ["Node", "Service", "Task"],
  },
  {
    name: "summary",
    iri: "urn:cetacean:summary",
    description: "Severity summary (critical/warning/info counts).",
    expectedType: "Object",
    usedOn: ["RecommendationCollection"],
  },
  {
    name: "task",
    iri: "urn:cetacean:task",
    description: "The Docker task object, enriched with ServiceName and NodeHostname.",
    expectedType: "Object",
    usedOn: ["Task"],
  },
  {
    name: "taskCount",
    iri: "urn:cetacean:taskCount",
    description: "Number of tasks in the cluster.",
    expectedType: "Integer",
    usedOn: ["Cluster"],
  },
  {
    name: "tasks",
    iri: "urn:cetacean:tasks",
    description: "The list of tasks belonging to a service or running on a node.",
    expectedType: "Array of Task",
    usedOn: ["Service", "Node", "Stack"],
    container: "@list",
  },
  {
    name: "tasksByState",
    iri: "urn:cetacean:tasksByState",
    description: "Task counts grouped by state.",
    expectedType: "Object",
    usedOn: ["Cluster"],
  },
  {
    name: "timestamp",
    iri: "urn:cetacean:timestamp",
    description: "When the event occurred.",
    expectedType: "DateTime",
    usedOn: ["HistoryEntry"],
  },
  {
    name: "total",
    iri: "urn:cetacean:total",
    description: "Total count of items.",
    expectedType: "Integer",
    usedOn: ["Collection", "SearchResult", "RecommendationCollection"],
  },
  {
    name: "totalCPU",
    iri: "urn:cetacean:totalCPU",
    description: "Total cluster CPU capacity (nanoCPUs).",
    expectedType: "Integer",
    usedOn: ["Cluster", "ClusterCapacity"],
  },
  {
    name: "totalMemory",
    iri: "urn:cetacean:totalMemory",
    description: "Total cluster memory capacity (bytes).",
    expectedType: "Integer",
    usedOn: ["Cluster", "ClusterCapacity"],
  },
  {
    name: "updatePolicy",
    iri: "urn:cetacean:updatePolicy",
    description: "Rolling update configuration for a service.",
    expectedType: "Object",
    usedOn: ["ServiceUpdatePolicy"],
  },
  {
    name: "updateStatus",
    iri: "urn:cetacean:updateStatus",
    description: "The status of a rolling update for a service, if one is in progress.",
    expectedType: "UpdateStatus",
    usedOn: ["Service"],
  },
  {
    name: "version",
    iri: "urn:cetacean:version",
    description: "Software version string.",
    expectedType: "String",
    usedOn: ["Health"],
  },
  {
    name: "volume",
    iri: "urn:cetacean:volume",
    description: "The Docker volume object.",
    expectedType: "Object",
    usedOn: ["Volume"],
  },
];

export const rfc9457Properties: Property[] = [
  {
    name: "type",
    iri: "urn:ietf:rfc:9457#type",
    description: "A URI reference identifying the problem type (RFC 9457).",
    expectedType: "URI",
    usedOn: ["ProblemDetail"],
  },
  {
    name: "title",
    iri: "urn:ietf:rfc:9457#title",
    description: "A short human-readable summary of the problem type (RFC 9457).",
    expectedType: "String",
    usedOn: ["ProblemDetail"],
  },
  {
    name: "status",
    iri: "urn:ietf:rfc:9457#status",
    description: "The HTTP status code for the problem (RFC 9457).",
    expectedType: "Integer",
    usedOn: ["ProblemDetail"],
  },
  {
    name: "detail",
    iri: "urn:ietf:rfc:9457#detail",
    description: "A human-readable explanation specific to this occurrence (RFC 9457).",
    expectedType: "String",
    usedOn: ["ProblemDetail"],
  },
  {
    name: "instance",
    iri: "urn:ietf:rfc:9457#instance",
    description: "A URI reference identifying the specific occurrence of the problem (RFC 9457).",
    expectedType: "URI",
    usedOn: ["ProblemDetail"],
  },
];

export const types: ResourceType[] = [
  // Primary resource types
  {
    name: "Collection",
    description: "A paginated list of resources.",
    endpoint: "All list endpoints",
    properties: ["items", "total", "limit", "offset"],
  },
  {
    name: "Node",
    description: "A Docker Swarm node (manager or worker).",
    endpoint: "/nodes/{id}",
    properties: ["node", "name", "role", "state", "availability", "tasks", "services"],
  },
  {
    name: "Service",
    description: "A Docker Swarm service.",
    endpoint: "/services/{id}",
    properties: ["service", "name", "mode", "replicas", "image", "ports", "networks", "aliases", "tasks", "updateStatus", "state", "changes", "integrations"],
  },
  {
    name: "Task",
    description: "A single running or completed container instance.",
    endpoint: "/tasks/{id}",
    properties: ["task", "state", "slot", "image", "hostname"],
  },
  {
    name: "Stack",
    description: "A group of services deployed together via `com.docker.stack.namespace` labels.",
    endpoint: "/stacks/{name}",
    properties: ["stack", "name", "tasks"],
  },
  {
    name: "Config",
    description: "A Docker Swarm config object.",
    endpoint: "/configs/{id}",
    properties: ["config", "name", "services"],
  },
  {
    name: "Secret",
    description: "A Docker Swarm secret (data always redacted).",
    endpoint: "/secrets/{id}",
    properties: ["secret", "name", "services"],
  },
  {
    name: "Network",
    description: "A Docker network.",
    endpoint: "/networks/{id}",
    properties: ["network", "name", "driver", "scope", "services"],
  },
  {
    name: "Volume",
    description: "A Docker volume.",
    endpoint: "/volumes/{name}",
    properties: ["volume", "name", "driver", "scope", "services"],
  },
  {
    name: "Plugin",
    description: "An installed Docker plugin.",
    endpoint: "/plugins/{name}",
    properties: ["plugin", "name"],
  },
  {
    name: "Cluster",
    description: "Cluster-wide overview with counts and resource totals.",
    endpoint: "/cluster",
    properties: [
      "nodeCount", "serviceCount", "taskCount", "stackCount",
      "nodesReady", "nodesDown", "nodesDraining",
      "servicesConverged", "servicesDegraded",
      "reservedCPU", "reservedMemory", "totalCPU", "totalMemory",
      "tasksByState", "prometheusConfigured",
    ],
  },
  {
    name: "Swarm",
    description: "Swarm configuration: join tokens, Raft config, CA config.",
    endpoint: "/swarm",
    properties: ["managerAddr"],
  },
  // Sub-resource types (service configuration endpoints)
  {
    name: "ServiceEnv",
    description: "Service environment variables.",
    endpoint: "/services/{id}/env",
    properties: ["env"],
  },
  {
    name: "ServicePorts",
    description: "Service port bindings.",
    endpoint: "/services/{id}/ports",
    properties: ["ports"],
  },
  {
    name: "ServiceLabels",
    description: "Service labels.",
    endpoint: "/services/{id}/labels",
    properties: ["labels"],
  },
  {
    name: "ServiceResources",
    description: "Service CPU/memory reservations and limits.",
    endpoint: "/services/{id}/resources",
    properties: ["resources"],
  },
  {
    name: "ServicePlacement",
    description: "Service placement constraints and preferences.",
    endpoint: "/services/{id}/placement",
    properties: ["placement"],
  },
  {
    name: "ServiceUpdatePolicy",
    description: "Rolling update configuration for a service.",
    endpoint: "/services/{id}/update-policy",
    properties: ["updatePolicy"],
  },
  {
    name: "ServiceRollbackPolicy",
    description: "Rollback configuration for a service.",
    endpoint: "/services/{id}/rollback-policy",
    properties: ["rollbackPolicy"],
  },
  {
    name: "ServiceLogDriver",
    description: "Log driver configuration for a service.",
    endpoint: "/services/{id}/log-driver",
    properties: ["logDriver"],
  },
  {
    name: "ServiceHealthcheck",
    description: "Healthcheck configuration for a service.",
    endpoint: "/services/{id}/healthcheck",
    properties: ["healthcheck"],
  },
  {
    name: "ServiceConfigs",
    description: "Config references attached to a service.",
    endpoint: "/services/{id}/configs",
    properties: ["configs"],
  },
  {
    name: "ServiceSecrets",
    description: "Secret references attached to a service.",
    endpoint: "/services/{id}/secrets",
    properties: ["secrets"],
  },
  {
    name: "ServiceNetworks",
    description: "Network attachments for a service.",
    endpoint: "/services/{id}/networks",
    properties: ["networks"],
  },
  {
    name: "ServiceMounts",
    description: "Mount configuration for a service.",
    endpoint: "/services/{id}/mounts",
    properties: ["mounts"],
  },
  {
    name: "ServiceMode",
    description: "Service scheduling mode and replica count.",
    endpoint: "/services/{id}/mode",
    properties: ["mode", "replicas"],
  },
  {
    name: "ServiceEndpointMode",
    description: "Service endpoint mode (vip or dnsrr).",
    endpoint: "/services/{id}/endpoint-mode",
    properties: ["endpointMode"],
  },
  {
    name: "NodeLabels",
    description: "Node labels.",
    endpoint: "/nodes/{id}/labels",
    properties: ["labels"],
  },
  {
    name: "NodeRole",
    description: "Node role in the swarm.",
    endpoint: "/nodes/{id}/role",
    properties: ["role", "isLeader", "managerCount"],
  },
  // Utility / derived types
  {
    name: "ClusterCapacity",
    description: "Cluster resource capacity: max single-node values and totals.",
    endpoint: "/cluster/capacity",
    properties: ["maxNodeCPU", "maxNodeMemory", "totalCPU", "totalMemory", "nodeCount"],
  },
  {
    name: "SearchResult",
    description: "Cross-resource search results.",
    endpoint: "/search",
    properties: ["query", "results", "counts", "total"],
  },
  {
    name: "RecommendationCollection",
    description: "Cluster health recommendations from the recommendation engine.",
    endpoint: "/recommendations",
    properties: ["items", "total", "summary", "computedAt"],
  },
  {
    name: "HistoryEntry",
    description: "A resource change event from the history ring buffer or SSE stream.",
    endpoint: "/history, /events",
    properties: ["kind", "action", "resourceId", "timestamp", "name"],
  },
  {
    name: "ServiceRef",
    description: "A cross-reference to a service (used in config/secret/network/volume detail responses).",
    endpoint: "Embedded in detail responses",
    properties: ["name"],
  },
  {
    name: "Health",
    description: "Health check response with build metadata and operations level.",
    endpoint: "/-/health",
    properties: ["version", "commit", "buildDate", "operationsLevel"],
  },
  {
    name: "ProblemDetail",
    description: "An error response following RFC 9457 Problem Details.",
    endpoint: "Error responses",
    properties: ["type", "title", "status", "detail", "instance", "requestId"],
  },
];

/** Build the JSON-LD context document from the property definitions. */
export function buildContext(): Record<string, unknown> {
  const ctx: Record<string, unknown> = {
    "@vocab": "urn:cetacean:",
  };

  for (const prop of [...properties, ...rfc9457Properties]) {
    ctx[prop.name] = prop.container ? { "@container": prop.container } : prop.iri;
  }

  return { "@context": ctx };
}
