#!/usr/bin/env bash
# Commits regenerated SBOM artifacts to a pull request branch, signed, and asks
# for the CI run that commit cannot start on its own.
#
# Uses the createCommitOnBranch GraphQL mutation rather than `git commit && git
# push`, for two reasons: GitHub GPG-signs commits authored through the API, so
# the result is Verified without a signing key in CI secrets; and the mutation
# takes expectedHeadOid, so a branch that moved since the checkout rejects the
# write instead of racing it.
#
# Usage: commit-sbom.sh <branch> <expected-head-oid> [--dry-run]
#
# Reads GH_TOKEN/GITHUB_TOKEN and GITHUB_REPOSITORY from the environment, as
# `gh` does. With --dry-run it prints the mutation variables and exits, which is
# how the payload construction is tested off CI.
#
# Every payload passes through a file rather than an argument: the artifacts run
# to megabytes once base64-encoded, and putting that on a command line exceeds
# ARG_MAX.
set -euo pipefail

# The artifacts `make sbom` owns. Kept in step with the same list in the
# Makefile's sbom-check target and in .githooks/pre-commit.
files=(
  internal/api/sbom/sbom.cdx.json
  internal/api/sbom/licensetexts.json
  internal/api/sbom/notices.txt
  THIRD_PARTY_LICENSES
)

branch="${1:?usage: commit-sbom.sh <branch> <expected-head-oid> [--dry-run]}"
expected_head_oid="${2:?usage: commit-sbom.sh <branch> <expected-head-oid> [--dry-run]}"
dry_run="${3:-}"

repository="${GITHUB_REPOSITORY:?GITHUB_REPOSITORY is required}"

# Only send what actually changed. A dependency bump usually rewrites one or two
# of these, and the mutation replaces whatever it is given.
changed=()
for file in "${files[@]}"; do
  if ! git diff --quiet -- "$file"; then
    changed+=("$file")
  fi
done

if [ ${#changed[@]} -eq 0 ]; then
  echo "SBOM is already up to date; nothing to commit." >&2
  exit 0
fi

# Progress goes to stderr: --dry-run writes the payload to stdout.
echo "SBOM drift in: ${changed[*]}" >&2

workdir=$(mktemp -d)
trap 'rm -rf "$workdir"' EXIT

# One {path, contents} document per changed file. base64 without line wrapping:
# GNU coreutils takes -w0 and BSD does not, so strip newlines instead of
# branching on the platform.
index=0
for file in "${changed[@]}"; do
  base64 <"$file" | tr -d '\n' >"$workdir/contents"

  jq -n \
    --arg path "$file" \
    --rawfile contents "$workdir/contents" \
    '{path: $path, contents: $contents}' >"$workdir/addition-$index.json"

  index=$((index + 1))
done

jq -s . "$workdir"/addition-*.json >"$workdir/additions.json"

jq -n \
  --arg repository "$repository" \
  --arg branch "$branch" \
  --arg expectedHeadOid "$expected_head_oid" \
  --slurpfile additions "$workdir/additions.json" \
  '{
     input: {
       branch: {
         repositoryNameWithOwner: $repository,
         branchName: $branch
       },
       message: {
         headline: "chore(sbom): regenerate for dependency changes",
         body: "Regenerated by CI because a dependency manifest changed. cyclonedx-gomod cannot run in a linked worktree and Dependabot cannot run `make sbom`, so the committed SBOM is kept current here rather than by the author."
       },
       expectedHeadOid: $expectedHeadOid,
       fileChanges: { additions: $additions[0] }
     }
   }' >"$workdir/variables.json"

if [ "$dry_run" = "--dry-run" ]; then
  cat "$workdir/variables.json"
  exit 0
fi

read -r -d '' mutation <<'GRAPHQL' || true
mutation ($input: CreateCommitOnBranchInput!) {
  createCommitOnBranch(input: $input) {
    commit { oid url }
  }
}
GRAPHQL

# --input takes the whole body (query plus variables) on stdin.
#
# The mutation is allowed to fail one specific way without failing the job. A
# branch that advanced since checkout makes expectedHeadOid stale, and the write
# is then correctly refused — that is the guard working, not a fault, and the
# run for the newer commit regenerates the SBOM anyway. Turning that race into a
# red check would report a problem that no longer exists. Every other error
# still fails, because it means the SBOM genuinely could not be committed.
set +e
response=$(
  jq -n \
    --arg query "$mutation" \
    --slurpfile variables "$workdir/variables.json" \
    '{query: $query, variables: $variables[0]}' |
    gh api graphql --input - 2>&1
)
status=$?
set -e

if [ $status -ne 0 ]; then
  # GitHub words this "Expected branch to point to ... but it did not."
  if printf '%s' "$response" | grep -qi 'expected branch to point to'; then
    echo "::warning::$branch advanced while the SBOM was being regenerated; skipping the commit. The run for the newer commit will regenerate it."
    echo "$response" >&2
    exit 0
  fi

  echo "$response" >&2
  exit $status
fi

echo "Committed regenerated SBOM to $branch." >&2

# That commit was authored with GITHUB_TOKEN, and GitHub raises no event for
# those — so the run that would put this branch's required checks on the new
# head never starts. The pull request is then blocked on checks that passed on
# the commit before it and can never appear on this one, until someone asks for
# a run by hand. workflow_dispatch is the documented exception to that
# suppression, the same one open-sbom-pr.sh relies on.
#
# This cannot recur: the dispatched run reports event_name workflow_dispatch,
# and the step that calls this script is gated on pull_request, so it commits
# nothing and dispatches nothing.
#
# Best effort, like the auto-merge in open-sbom-pr.sh. The commit is the job and
# it succeeded; a run that has to be started by hand is a worse outcome than
# this warning, not a reason to report the SBOM as uncommitted.
if ! gh workflow run ci.yml --repo "$repository" --ref "$branch"; then
  echo "::warning::Committed the SBOM to $branch but could not dispatch a run for it. Its required checks will stay on the previous commit; re-run CI on the branch to clear them."
fi
