#!/usr/bin/env bash
# Opens (or refreshes) a pull request that brings the committed SBOM back in
# step with main.
#
# This is the backstop for the one PR flow that cannot carry its own SBOM
# commit: Dependabot stops updating a branch that holds a commit it did not
# author, so committing the regenerated SBOM onto its branch would cost us
# `@dependabot rebase` for the life of the PR. Those PRs are therefore merged
# with the SBOM still stale, and the drift is repaired here, on a branch of our
# own, one CI run later.
#
# Usage: open-sbom-pr.sh <base-sha> [--dry-run]
#
# Expects `make sbom` to have run already, so any drift is sitting in the
# working tree. Reads GH_TOKEN/GITHUB_TOKEN and GITHUB_REPOSITORY from the
# environment, as `gh` does. With --dry-run it reports what it would do and
# exits without touching the remote.
set -euo pipefail

branch=chore/sbom-sync

base_sha="${1:?usage: open-sbom-pr.sh <base-sha> [--dry-run]}"
dry_run="${2:-}"

repository="${GITHUB_REPOSITORY:?GITHUB_REPOSITORY is required}"
script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

if make -s -C "$script_dir/.." sbom-verify >/dev/null 2>&1; then
  echo "SBOM is already current on main; nothing to open."
  exit 0
fi

echo "SBOM drift on main; opening $branch."

if [ "$dry_run" = "--dry-run" ]; then
  echo "would reset $branch to $base_sha, commit the artifacts, open a PR and dispatch CI"
  exit 0
fi

# Point the branch at the commit that drifted. Force, because a previous sync PR
# may still be open against an older main — its content is superseded by this
# run, and the open pull request simply follows the branch.
if gh api "repos/$repository/git/ref/heads/$branch" >/dev/null 2>&1; then
  gh api --method PATCH "repos/$repository/git/refs/heads/$branch" \
    -f sha="$base_sha" -F force=true >/dev/null
else
  gh api --method POST "repos/$repository/git/refs" \
    -f ref="refs/heads/$branch" -f sha="$base_sha" >/dev/null
fi

# Same signed-commit path the pull request flow uses.
"$script_dir/commit-sbom.sh" "$branch" "$base_sha"

if [ -z "$(gh pr list --repo "$repository" --head "$branch" --state open --json number --jq '.[].number')" ]; then
  gh pr create --repo "$repository" --base main --head "$branch" \
    --title "chore(sbom): regenerate for dependency changes" \
    --body "The committed SBOM drifted from the dependency manifests on main.

Dependabot pull requests deliberately do not carry their own SBOM commit: a
branch holding a commit Dependabot did not author can no longer be rebased by
it, which costs more than the drift does. This repairs the difference instead.

Generated by the \`sbom-sync\` job in CI. No hand edits — if this conflicts,
close it and the next push to main will open a fresh one."
fi

# A pull request opened with GITHUB_TOKEN raises no `pull_request` event, so the
# required checks would never run and the PR could never merge. workflow_dispatch
# is the documented exception to that suppression, so ask for the run explicitly.
gh workflow run ci.yml --repo "$repository" --ref "$branch"

# Best effort: auto-merge is a repository setting and the branch rules may want
# something this PR cannot satisfy on its own. Leaving it open for a human is a
# fine outcome; failing the run over it is not.
if ! gh pr merge --repo "$repository" "$branch" --auto --squash 2>&1; then
  echo "::warning::Could not enable auto-merge on $branch; merge it by hand."
fi

echo "Opened or refreshed $branch."
