package config

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"slices"
	"strings"
	"testing"
)

var updateKnownEnvVars = flag.Bool("update", false, "rewrite "+knownEnvVarsFile)

const knownEnvVarsFile = "knownenv_gen.go"

// TestKnownEnvVarsMatchTheLoader derives the names CheckEnv accepts from the
// loader's own call sites, the scan TestConfigEnvVarsMatchDocumentation holds
// against the docs, so a new setting cannot be read yet refused.
func TestKnownEnvVarsMatchTheLoader(t *testing.T) {
	names := literalEnvVars(t)
	for name := range resolveSecretVars(t) {
		names[name+"_FILE"] = true
	}

	sorted := make([]string, 0, len(names))
	for name := range names {
		sorted = append(sorted, name)
	}
	slices.Sort(sorted)

	var b strings.Builder
	b.WriteString("// Code generated by TestKnownEnvVarsMatchTheLoader -update. DO NOT EDIT.\n\n")
	b.WriteString("package config\n\nvar knownEnvVars = map[string]bool{\n")
	for _, name := range sorted {
		fmt.Fprintf(&b, "\t%q: true,\n", name)
	}
	b.WriteString("}\n")

	want, err := format.Source([]byte(b.String()))
	if err != nil {
		t.Fatalf("format: %v", err)
	}

	if *updateKnownEnvVars {
		if err := os.WriteFile(knownEnvVarsFile, want, 0o600); err != nil {
			t.Fatal(err)
		}
		return
	}

	got, err := os.ReadFile(knownEnvVarsFile)
	if err != nil || string(got) != string(want) {
		t.Errorf(
			"%s is stale; run go test ./internal/config -run TestKnownEnvVarsMatchTheLoader -update",
			knownEnvVarsFile,
		)
	}
}

func TestCheckEnv(t *testing.T) {
	t.Run("settings, _FILE variants and tooling variables pass", func(t *testing.T) {
		err := CheckEnv([]string{
			"PATH=/usr/bin",
			"CETACEAN_PPROF=true",
			"CETACEAN_AUTH_OIDC_CLIENT_SECRET_FILE=/run/secrets/oidc",
			"CETACEAN_CONFIG=/dev/null",
			"CETACEAN_SPEC_CLAIMS=/tmp/claims",
		})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
	})

	t.Run("unknown names are refused, sorted", func(t *testing.T) {
		err := CheckEnv([]string{
			"CETACEAN_SLEF_METRICS=false",
			"CETACEAN_LISTEN_ADDR=:9000",
			"CETACEAN_PPROF_FILE=/x",
			"CETACEAN_AUTH_HEADERS_TRUSTED_PROXIES=10.0.0.0/8",
		})
		if err == nil {
			t.Fatal("expected an error")
		}

		want := "CETACEAN_AUTH_HEADERS_TRUSTED_PROXIES, CETACEAN_PPROF_FILE, CETACEAN_SLEF_METRICS."
		if !strings.Contains(err.Error(), want) {
			t.Errorf("err = %v, want it to name %s", err, want)
		}
	})
}
